version: "3.8"

services:
  rabbit:
    image: rabbitmq:3.10.5-management
    container_name: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbit_data:/var/lib/rabbitmq/
      - rabbit_log:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge

volumes:
  rabbit_data:
    external: false
  rabbit_log:
    external: false

