version: "3"

networks:
  mynetwork:


services:
  db:
    image: mysql:5.7
    container_name: database
    restart: always
    environment:
      MYSQL_DATABASE: 'filedatabase'
      MYSQL_USER: 'file_user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./../../../../disks/sql:/var/lib/mysql
      - "./init-db/init-db.sql:/docker-entrypoint-initdb.d/1.sql:ro"
    networks:
      mynetwork:
    healthcheck:
      test: [ "CMD-SHELL", "mysql --user=root --password=$$MYSQL_ROOT_PASSWORD -e 'SHOW DATABASES;' || exit 1" ]
      interval: 60s
      timeout: 20s
      retries: 3
      start_period: 30s
